In [19]:
import requests
import pandas as pd
from pylab import *

%matplotlib inline

## Importing Dataset from Kaggle and Official OpenPowerlifting site

Alongside importing data we proceed to convert 'Date' to date-dtype, to cut and merge the dataset based on the timeseries. </br>
Additionally, we will define constants to be used throughout the cleaning process.

In [20]:
df = pd.read_csv('openpowerlifting.csv', sep=',', low_memory=False)
df.drop(['MeetName', 'MeetState', 'MeetCountry', 'Event', 'Division', 'IPFPoints', 'Country', 'Federation'], axis=1, inplace=True)
df2 = pd.read_csv('openpowerlifting-latest.csv', sep=',', low_memory=False)
df2.drop(['BirthYearClass', 'ParentFederation', 'MeetName', 'MeetState', 'MeetCountry', 'Event', 'Division', 'IPFPoints', 'Country', 'Federation'], axis=1, inplace=True)

cols = ['Squat1Kg','Squat2Kg','Squat3Kg','Squat4Kg','Best3SquatKg','Bench1Kg','Bench2Kg','Bench3Kg','Bench4Kg','Best3BenchKg','Deadlift1Kg','Deadlift2Kg','Deadlift3Kg','Deadlift4Kg','Best3DeadliftKg']
df['Date'] = pd.to_datetime(df2['Date'], format='%Y-%m-%d')
df2['Date'] = pd.to_datetime(df2['Date'], format='%Y-%m-%d')

date_limit = pd.to_datetime('2019-04-20', format='%Y-%m-%d')
df2.drop(df2[df2['Date'] <= date_limit].index, inplace=True)

df.append(df2)

,Name,Sex,Equipment,Age,AgeClass,BodyweightKg,WeightClassKg,Squat1Kg,Squat2Kg,Squat3Kg,...,Deadlift3Kg,Deadlift4Kg,Best3DeadliftKg,TotalKg,Place,Wilks,McCulloch,Glossbrenner,Tested,Date
0,Abbie Murphy,F,Wraps,29.0,24-34,59.80,60,80.0,92.5,105.0,...,130.0,NaN,130.0,290.0,4,324.16,324.16,286.42,NaN,2019-04-06
1,Abbie Tuong,F,Wraps,29.0,24-34,58.50,60,100.0,110.0,120.0,...,145.0,NaN,145.0,332.5,2,378.07,378.07,334.16,NaN,2019-04-06
2,Ainslee Hooper,F,Raw,40.0,40-44,55.40,56,NaN,NaN,NaN,...,NaN,NaN,NaN,32.5,1,38.56,38.56,34.12,NaN,2019-04-06
3,Amy Moldenhauer,F,Wraps,23.0,20-23,60.00,60,-105.0,-105.0,105.0,...,-140.0,NaN,132.5,310.0,3,345.61,345.61,305.37,NaN,2019-04-06
4,Andrea Rowan,F,Wraps,45.0,45-49,104.00,110,120.0,130.0,140.0,...,170.0,NaN,170.0,390.0,3,321.25,338.91,274.56,NaN,2019-04-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1860779,Alfredo Tatum,M,Raw,21.5,20-23,84.10,90,NaN,NaN,NaN,...,NaN,NaN,255.0,421.0,1,278.86,281.65,268.08,Yes,2019-10-19
1860780,Coby Carden,M,Raw,62.5,60-64,93.03,100,NaN,NaN,NaN,...,NaN,NaN,240.0,400.0,1,251.24,349.97,240.46,Yes,2019-10-19
1860781,Randale Lee Carnway,M,Raw,NaN,NaN,66.63,67.5,NaN,NaN,NaN,...,NaN,NaN,NaN,145.0,1,112.97,112.97,109.73,Yes,2019-10-19
1860782,Dustin Reid,M,Raw,NaN,NaN,130.09,140,NaN,NaN,NaN,...,NaN,NaN,NaN,110.0,1,62.21,62.21,59.42,Yes,2019-10-19
1860783,Greg Wheat,M,Raw,50.0,50-54,74.48,75,NaN,NaN,NaN,...,NaN,NaN,NaN,145.0,1,103.83,117.32,100.35,Yes,2019-10-19

## Cleaning the Data

In [21]:
df.drop_duplicates(inplace=True)
df[cols] = df[cols].clip(lower=0)
df[cols] = df[cols].fillna(0)
df.dropna(subset=['Age', 'Name'], inplace=True)
df.drop(df[df['Age'] < 18].index, inplace=True)
df.drop(df[df['Sex'] == "Mx"].index, inplace=True)
df.dropna(subset=['BodyweightKg'], axis=0, inplace=True)
df.drop(df[df['BodyweightKg']< 30].index, inplace=True)
df.reset_index(drop=True, inplace=True)
df

,Name,Sex,Equipment,Age,AgeClass,BodyweightKg,WeightClassKg,Squat1Kg,Squat2Kg,Squat3Kg,...,Deadlift3Kg,Deadlift4Kg,Best3DeadliftKg,TotalKg,Place,Wilks,McCulloch,Glossbrenner,Tested,Date
0,Abbie Murphy,F,Wraps,29.0,24-34,59.8,60,80.0,92.5,105.0,...,130.0,0.0,130.0,290.0,4,324.16,324.16,286.42,NaN,2019-04-06
1,Abbie Tuong,F,Wraps,29.0,24-34,58.5,60,100.0,110.0,120.0,...,145.0,0.0,145.0,332.5,2,378.07,378.07,334.16,NaN,2019-04-06
2,Ainslee Hooper,F,Raw,40.0,40-44,55.4,56,0.0,0.0,0.0,...,0.0,0.0,0.0,32.5,1,38.56,38.56,34.12,NaN,2019-04-06
3,Amy Moldenhauer,F,Wraps,23.0,20-23,60.0,60,0.0,0.0,105.0,...,0.0,0.0,132.5,310.0,3,345.61,345.61,305.37,NaN,2019-04-06
4,Andrea Rowan,F,Wraps,45.0,45-49,104.0,110,120.0,130.0,140.0,...,170.0,0.0,170.0,390.0,3,321.25,338.91,274.56,NaN,2019-04-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647654,Marian Cafalik,M,Raw,60.5,60-64,73.5,74,160.0,170.0,175.0,...,0.0,0.0,190.0,452.5,4,327.07,438.27,316.52,Yes,2011-10-15
647655,Marian Piwowarczyk,M,Raw,55.5,55-59,63.5,66,90.0,100.0,110.0,...,170.0,0.0,170.0,375.0,5,304.16,372.60,295.66,Yes,2011-10-15
647656,Andrzej Bryniarski,M,Raw,62.5,60-64,94.4,105,140.0,150.0,160.0,...,180.0,0.0,180.0,440.0,6,274.48,382.36,264.22,Yes,2011-10-15
647657,Stanisław Goroczko,M,Raw,63.5,60-64,80.8,83,0.0,0.0,0.0,...,0.0,0.0,0.0,NaN,DQ,NaN,NaN,NaN,Yes,2011-10-15
647658,Jan Sowa,M,Raw,70.5,70-74,82.0,83,0.0,115.0,0.0,...,0.0,0.0,0.0,NaN,DQ,NaN,NaN,NaN,Yes,2011-10-15

## Discretisation and Binning

In [22]:
conditions = [
    (df['Sex'] == 'F') & (df['BodyweightKg'] < 43),
    (df['Sex'] == 'F') & (df['BodyweightKg'] < 47),
    (df['Sex'] == 'F') & (df['BodyweightKg'] < 52),
    (df['Sex'] == 'F') & (df['BodyweightKg'] < 57),
    (df['Sex'] == 'F') & (df['BodyweightKg'] < 63),
    (df['Sex'] == 'F') & (df['BodyweightKg'] < 72),
    (df['Sex'] == 'F') & (df['BodyweightKg'] < 84),
    (df['Sex'] == 'F'),
    (df['Sex'] == 'M') & (df['BodyweightKg'] < 53),
    (df['Sex'] == 'M') & (df['BodyweightKg'] < 59),
    (df['Sex'] == 'M') & (df['BodyweightKg'] < 66),
    (df['Sex'] == 'M') & (df['BodyweightKg'] < 74),
    (df['Sex'] == 'M') & (df['BodyweightKg'] < 83),
    (df['Sex'] == 'M') & (df['BodyweightKg'] < 93),
    (df['Sex'] == 'M') & (df['BodyweightKg'] < 105),
    (df['Sex'] == 'M') & (df['BodyweightKg'] < 120),
    (df['Sex'] == 'M')]
choices = ['43','47','52','57','63','72','84','84+',
          '53','59','66','74','83','93','105','120','120+']
df['WeightClassKg'] = np.select(conditions, choices, default='120+')

In [24]:
df.describe()

,Age,BodyweightKg,Squat1Kg,Squat2Kg,Squat3Kg,Squat4Kg,Best3SquatKg,Bench1Kg,Bench2Kg,Bench3Kg,...,Best3BenchKg,Deadlift1Kg,Deadlift2Kg,Deadlift3Kg,Deadlift4Kg,Best3DeadliftKg,TotalKg,Wilks,McCulloch,Glossbrenner
count,647659.000000,647659.000000,647659.000000,647659.000000,647659.000000,647659.000000,647659.000000,647659.000000,647659.000000,647659.000000,...,647659.000000,647659.000000,647659.000000,647659.000000,647659.000000,647659.000000,608623.000000,608623.000000,608623.000000,608623.000000
mean,33.538063,87.053437,55.594579,52.734592,40.765174,0.509610,122.876707,62.081543,54.679837,32.940174,...,120.415142,73.204577,67.570407,42.417700,1.181065,146.625914,405.862923,289.566330,301.037365,272.881661
std,12.829499,22.861399,90.473781,91.614594,84.900217,10.546602,110.083451,73.102399,73.931469,64.836638,...,67.250794,100.038255,101.447427,86.709333,15.889595,109.106519,227.027820,143.159929,145.534596,136.072042
min,18.000000,30.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000,5.760000,6.180000,5.500000
25%,23.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,72.500000,0.000000,0.000000,0.000000,0.000000,0.000000,202.500000,135.880000,144.130000,129.080000
50%,30.000000,83.900000,0.000000,0.000000,0.000000,0.000000,130.000000,0.000000,0.000000,0.000000,...,125.000000,0.000000,0.000000,0.000000,0.000000,170.000000,380.000000,319.610000,332.400000,297.420000
75%,41.500000,100.000000,115.000000,102.500000,0.000000,0.000000,210.000000,122.500000,115.000000,0.000000,...,165.000000,165.000000,150.000000,0.000000,0.000000,237.500000,585.000000,400.230000,413.910000,379.380000
max,97.000000,258.000000,555.000000,566.990000,560.000000,505.500000,575.000000,467.500000,485.340000,478.540000,...,488.500000,450.000000,440.000000,457.500000,418.000000,457.500000,1367.500000,779.380000,804.400000,742.960000