In [31]:
import pandas as pd
from pylab import *

%matplotlib inline

## Importing Dataset from Kaggle and Official OpenPowerlifting site

Alongside importing data we proceed to convert 'Date' to date-dtype, to cut and merge the dataset based on the timeseries. </br>
Additionally, we will define constants to be used throughout the cleaning process.

In [32]:
df = pd.read_csv('openpowerlifting.csv', sep=',', low_memory=False)
df.drop(['MeetName', 'MeetState', 'MeetCountry', 'Division', 'IPFPoints', 'Country', 'Federation'], axis=1, inplace=True)
df2 = pd.read_csv('openpowerlifting-latest.csv', sep=',', low_memory=False)
df2.drop(['BirthYearClass', 'ParentFederation', 'MeetName', 'MeetState', 'MeetCountry', 'Division', 'IPFPoints', 'Country', 'Federation'], axis=1, inplace=True)

cols = ['Squat1Kg','Squat2Kg','Squat3Kg','Squat4Kg','Best3SquatKg','Bench1Kg','Bench2Kg','Bench3Kg','Bench4Kg','Best3BenchKg','Deadlift1Kg','Deadlift2Kg','Deadlift3Kg','Deadlift4Kg','Best3DeadliftKg']
df['Date'] = pd.to_datetime(df2['Date'], format='%Y-%m-%d')
df2['Date'] = pd.to_datetime(df2['Date'], format='%Y-%m-%d')

date_limit = pd.to_datetime('2019-04-20', format='%Y-%m-%d')
df2.drop(df2[df2['Date'] <= date_limit].index, inplace=True)

df.append(df2)

,Name,Sex,Event,Equipment,Age,AgeClass,BodyweightKg,WeightClassKg,Squat1Kg,Squat2Kg,...,Deadlift3Kg,Deadlift4Kg,Best3DeadliftKg,TotalKg,Place,Wilks,McCulloch,Glossbrenner,Tested,Date
0,Abbie Murphy,F,SBD,Wraps,29.0,24-34,59.80,60,80.0,92.5,...,130.0,NaN,130.0,290.0,4,324.16,324.16,286.42,NaN,2019-04-06
1,Abbie Tuong,F,SBD,Wraps,29.0,24-34,58.50,60,100.0,110.0,...,145.0,NaN,145.0,332.5,2,378.07,378.07,334.16,NaN,2019-04-06
2,Ainslee Hooper,F,B,Raw,40.0,40-44,55.40,56,NaN,NaN,...,NaN,NaN,NaN,32.5,1,38.56,38.56,34.12,NaN,2019-04-06
3,Amy Moldenhauer,F,SBD,Wraps,23.0,20-23,60.00,60,-105.0,-105.0,...,-140.0,NaN,132.5,310.0,3,345.61,345.61,305.37,NaN,2019-04-06
4,Andrea Rowan,F,SBD,Wraps,45.0,45-49,104.00,110,120.0,130.0,...,170.0,NaN,170.0,390.0,3,321.25,338.91,274.56,NaN,2019-04-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1860779,Alfredo Tatum,M,BD,Raw,21.5,20-23,84.10,90,NaN,NaN,...,NaN,NaN,255.0,421.0,1,278.86,281.65,268.08,Yes,2019-10-19
1860780,Coby Carden,M,BD,Raw,62.5,60-64,93.03,100,NaN,NaN,...,NaN,NaN,240.0,400.0,1,251.24,349.97,240.46,Yes,2019-10-19
1860781,Randale Lee Carnway,M,B,Raw,NaN,NaN,66.63,67.5,NaN,NaN,...,NaN,NaN,NaN,145.0,1,112.97,112.97,109.73,Yes,2019-10-19
1860782,Dustin Reid,M,B,Raw,NaN,NaN,130.09,140,NaN,NaN,...,NaN,NaN,NaN,110.0,1,62.21,62.21,59.42,Yes,2019-10-19
1860783,Greg Wheat,M,B,Raw,50.0,50-54,74.48,75,NaN,NaN,...,NaN,NaN,NaN,145.0,1,103.83,117.32,100.35,Yes,2019-10-19

In [33]:
df.describe()

,Age,BodyweightKg,Squat1Kg,Squat2Kg,Squat3Kg,Squat4Kg,Best3SquatKg,Bench1Kg,Bench2Kg,Bench3Kg,...,Best3BenchKg,Deadlift1Kg,Deadlift2Kg,Deadlift3Kg,Deadlift4Kg,Best3DeadliftKg,TotalKg,Wilks,McCulloch,Glossbrenner
count,757527.000000,1.406622e+06,337580.000000,333349.000000,323842.000000,3696.000000,1.031450e+06,499779.000000,493486.000000,478485.000000,...,1.276181e+06,363544.000000,356023.000000,339947.000000,9246.000000,1.081808e+06,1.313184e+06,1.304407e+06,1.304254e+06,1.304407e+06
mean,31.501570,8.422503e+01,114.102442,92.155846,30.056842,71.356870,1.740049e+02,83.892373,55.065745,-18.520481,...,1.165444e+02,162.700840,130.228378,12.995484,78.914945,1.872585e+02,3.956148e+02,2.882247e+02,2.960682e+02,2.718484e+02
std,13.371707,2.322011e+01,147.143021,173.701524,200.413385,194.522045,6.923931e+01,105.196350,130.302229,144.225726,...,5.483622e+01,108.681438,162.680134,215.052488,192.605159,6.232821e+01,2.011420e+02,1.231805e+02,1.249700e+02,1.175571e+02
min,0.000000,1.510000e+01,-555.000000,-580.000000,-600.500000,-550.000000,-4.775000e+02,-480.000000,-507.500000,-575.000000,...,-5.225000e+02,-461.000000,-470.000000,-587.500000,-461.000000,-4.100000e+02,2.500000e+00,1.470000e+00,1.470000e+00,1.410000e+00
25%,21.000000,6.670000e+01,90.000000,68.000000,-167.500000,-107.840000,1.224700e+02,57.500000,-52.500000,-140.000000,...,7.484000e+01,125.000000,115.000000,-210.000000,-110.000000,1.383500e+02,2.325000e+02,1.979000e+02,2.048200e+02,1.828100e+02
50%,28.000000,8.180000e+01,147.500000,145.000000,110.000000,135.000000,1.678300e+02,105.000000,95.000000,-60.000000,...,1.111300e+02,180.000000,177.500000,117.500000,145.150000,1.850000e+02,3.787500e+02,3.052000e+02,3.120300e+02,2.859400e+02
75%,40.000000,9.915000e+01,200.000000,205.000000,192.500000,205.000000,2.175000e+02,145.000000,145.000000,117.500000,...,1.500000e+02,226.800000,230.000000,205.000000,210.000000,2.300000e+02,5.400000e+02,3.745600e+02,3.837600e+02,3.552800e+02
max,97.000000,2.580000e+02,555.000000,566.990000,560.000000,505.500000,5.750000e+02,467.500000,487.500000,478.540000,...,4.885000e+02,450.000000,460.400000,457.500000,418.000000,5.850000e+02,1.367500e+03,7.793800e+02,8.044000e+02,7.429600e+02

In [34]:
df[df['Place'] == "DQ"].count()

Name               99758
Sex                99758
Event              99758
Equipment          99758
Age                43963
AgeClass           45257
BodyweightKg       99118
WeightClassKg      99426
Squat1Kg           19094
Squat2Kg           18369
Squat3Kg           17357
Squat4Kg              59
Best3SquatKg       40719
Bench1Kg           25188
Bench2Kg           23413
Bench3Kg           21981
Bench4Kg              76
Best3BenchKg       23692
Deadlift1Kg        11925
Deadlift2Kg         9908
Deadlift3Kg         8957
Deadlift4Kg           58
Best3DeadliftKg    14872
TotalKg                0
Place              99758
Wilks                  0
McCulloch              0
Glossbrenner           0
Tested             79694
Date               99758
dtype: int64

## Cleaning the Data

In [35]:
df.drop_duplicates(inplace=True)
# df[cols] = df[cols].clip(lower=0)
# df[cols] = df[cols].fillna(0)
df.dropna(subset=['Age', 'Name'], inplace=True)
df.drop(df[df['Age'] < 18].index, inplace=True)
df.drop(df[df['Sex'] == "Mx"].index, inplace=True)
df.drop(df[df['Place'] == "DQ"].index, inplace= True)
df.dropna(subset=['Wilks'], axis=0, inplace=True)
df.dropna(subset=['BodyweightKg'], axis=0, inplace=True)
df.drop(df[df['BodyweightKg']< 30].index, inplace=True)
df.reset_index(drop=True, inplace=True)
df

,Name,Sex,Event,Equipment,Age,AgeClass,BodyweightKg,WeightClassKg,Squat1Kg,Squat2Kg,...,Deadlift3Kg,Deadlift4Kg,Best3DeadliftKg,TotalKg,Place,Wilks,McCulloch,Glossbrenner,Tested,Date
0,Abbie Murphy,F,SBD,Wraps,29.0,24-34,59.8,60,80.0,92.5,...,130.0,NaN,130.0,290.0,4,324.16,324.16,286.42,NaN,2019-04-06
1,Abbie Tuong,F,SBD,Wraps,29.0,24-34,58.5,60,100.0,110.0,...,145.0,NaN,145.0,332.5,2,378.07,378.07,334.16,NaN,2019-04-06
2,Ainslee Hooper,F,B,Raw,40.0,40-44,55.4,56,NaN,NaN,...,NaN,NaN,NaN,32.5,1,38.56,38.56,34.12,NaN,2019-04-06
3,Amy Moldenhauer,F,SBD,Wraps,23.0,20-23,60.0,60,-105.0,-105.0,...,-140.0,NaN,132.5,310.0,3,345.61,345.61,305.37,NaN,2019-04-06
4,Andrea Rowan,F,SBD,Wraps,45.0,45-49,104.0,110,120.0,130.0,...,170.0,NaN,170.0,390.0,3,321.25,338.91,274.56,NaN,2019-04-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
608618,Adam Jasiński,M,SBD,Raw,65.5,65-69,78.0,83,195.0,202.5,...,-212.5,NaN,207.5,537.5,2,372.98,552.01,360.48,Yes,2011-10-15
608619,Włodzimierz Żmijewski,M,SBD,Raw,67.5,65-69,72.7,74,185.0,195.0,...,-250.5,NaN,235.0,505.0,3,367.91,567.68,356.14,Yes,2011-10-15
608620,Marian Cafalik,M,SBD,Raw,60.5,60-64,73.5,74,160.0,170.0,...,-195.0,NaN,190.0,452.5,4,327.07,438.27,316.52,Yes,2011-10-15
608621,Marian Piwowarczyk,M,SBD,Raw,55.5,55-59,63.5,66,90.0,100.0,...,170.0,NaN,170.0,375.0,5,304.16,372.60,295.66,Yes,2011-10-15
608622,Andrzej Bryniarski,M,SBD,Raw,62.5,60-64,94.4,105,140.0,150.0,...,180.0,NaN,180.0,440.0,6,274.48,382.36,264.22,Yes,2011-10-15

## Discretisation and Binning

In [36]:
conditions = [
    (df['Sex'] == 'F') & (df['BodyweightKg'] < 43),
    (df['Sex'] == 'F') & (df['BodyweightKg'] < 47),
    (df['Sex'] == 'F') & (df['BodyweightKg'] < 52),
    (df['Sex'] == 'F') & (df['BodyweightKg'] < 57),
    (df['Sex'] == 'F') & (df['BodyweightKg'] < 63),
    (df['Sex'] == 'F') & (df['BodyweightKg'] < 72),
    (df['Sex'] == 'F') & (df['BodyweightKg'] < 84),
    (df['Sex'] == 'F'),
    (df['Sex'] == 'M') & (df['BodyweightKg'] < 53),
    (df['Sex'] == 'M') & (df['BodyweightKg'] < 59),
    (df['Sex'] == 'M') & (df['BodyweightKg'] < 66),
    (df['Sex'] == 'M') & (df['BodyweightKg'] < 74),
    (df['Sex'] == 'M') & (df['BodyweightKg'] < 83),
    (df['Sex'] == 'M') & (df['BodyweightKg'] < 93),
    (df['Sex'] == 'M') & (df['BodyweightKg'] < 105),
    (df['Sex'] == 'M') & (df['BodyweightKg'] < 120),
    (df['Sex'] == 'M')]
choices = ['43','47','52','57','63','72','84','84+',
          '53','59','66','74','83','93','105','120','120+']
df['WeightClassKg'] = np.select(conditions, choices, default='120+')

In [37]:
df.to_csv('data.csv', index=False)