# Classification using Neural Network by Sex

In [18]:
from pylab import *
import pandas as pd
import random
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split


from sklearn import *
import keras

%matplotlib inline
# columns = ['BodyweightKg', 'Age', 'Squat1Kg', 'Squat2Kg', 'Squat3Kg', 'Squat4Kg', 'Best3SquatKg', 'Bench1Kg', 'Bench2Kg', 'Bench3Kg', 'Bench4Kg', 'Best3BenchKg', 'Deadlift1Kg', 'Deadlift2Kg', 'Deadlift3Kg', 'Deadlift4Kg', 'Best3DeadliftKg']

dv = pd.read_csv('data.csv')
print(dv)

                         Name Sex Event Equipment   Age AgeClass  \
0                Abbie Murphy   F   SBD     Wraps  29.0    24-34
1                 Abbie Tuong   F   SBD     Wraps  29.0    24-34
2              Ainslee Hooper   F     B       Raw  40.0    40-44
3             Amy Moldenhauer   F   SBD     Wraps  23.0    20-23
4                Andrea Rowan   F   SBD     Wraps  45.0    45-49
...                       ...  ..   ...       ...   ...      ...
608618          Adam Jasiński   M   SBD       Raw  65.5    65-69
608619  Włodzimierz Żmijewski   M   SBD       Raw  67.5    65-69
608620         Marian Cafalik   M   SBD       Raw  60.5    60-64
608621     Marian Piwowarczyk   M   SBD       Raw  55.5    55-59
608622     Andrzej Bryniarski   M   SBD       Raw  62.5    60-64

        BodyweightKg WeightClassKg  Squat1Kg  Squat2Kg  ...  Deadlift3Kg  \
0               59.8            63      80.0      92.5  ...        130.0
1               58.5            63     100.0     110.0  ...        145.0
2               55.4            57       NaN       NaN  ...          NaN
3               60.0            63    -105.0    -105.0  ...       -140.0
4              104.0           84+     120.0     130.0  ...        170.0
...              ...           ...       ...       ...  ...          ...
608618          78.0            83     195.0     202.5  ...       -212.5
608619          72.7            74     185.0     195.0  ...       -250.5
608620          73.5            74     160.0     170.0  ...       -195.0
608621          63.5            66      90.0     100.0  ...        170.0
608622          94.4           105     140.0     150.0  ...        180.0

        Deadlift4Kg  Best3DeadliftKg  TotalKg  Place   Wilks  McCulloch  \
0               NaN            130.0    290.0      4  324.16     324.16
1               NaN            145.0    332.5      2  378.07     378.07
2               NaN              NaN     32.5      1   38.56      38.56
3               NaN            132.5    310.0      3  345.61     345.61
4               NaN            170.0    390.0      3  321.25     338.91
...             ...              ...      ...    ...     ...        ...
608618          NaN            207.5    537.5      2  372.98     552.01
608619          NaN            235.0    505.0      3  367.91     567.68
608620          NaN            190.0    452.5      4  327.07     438.27
608621          NaN            170.0    375.0      5  304.16     372.60
608622          NaN            180.0    440.0      6  274.48     382.36

        Glossbrenner  Tested        Date
0             286.42     NaN  2019-04-06
1             334.16     NaN  2019-04-06
2              34.12     NaN  2019-04-06
3             305.37     NaN  2019-04-06
4             274.56     NaN  2019-04-06
...              ...     ...         ...
608618        360.48     Yes  2011-10-15
608619        356.14     Yes  2011-10-15
608620        316.52     Yes  2011-10-15
608621        295.66     Yes  2011-10-15
608622        264.22     Yes  2011-10-15

[608623 rows x 30 columns]

In [19]:
# Dropping columns not needed for this test
dv = dv.drop(columns=['Name', 'AgeClass', 
                         'Place', 'Tested',
                          'Date', 'McCulloch', 'Glossbrenner',
                          'WeightClassKg'])

dv.columns
dv.isnull().sum()

Sex                     0
Event                   0
Equipment               0
Age                     0
BodyweightKg            0
Squat1Kg           380725
Squat2Kg           383286
Squat3Kg           389599
Squat4Kg           606156
Best3SquatKg       211003
Bench1Kg           255162
Bench2Kg           258522
Bench3Kg           269003
Bench4Kg           602385
Best3BenchKg        38576
Deadlift1Kg        353567
Deadlift2Kg        357594
Deadlift3Kg        368866
Deadlift4Kg        602897
Best3DeadliftKg    162908
TotalKg                 0
Wilks                   0
dtype: int64

In [20]:
dv[dv['Event'] == 'SBD'].shape

(395708, 22)

In [21]:
dv = dv.where(dv['Event'] == 'SBD') # --> All lifts subset
dv.dropna(subset=['Event'] ,inplace=True)
dv.reset_index(drop=True, inplace=True)
# dv.apply(lambda x: np.clip(x, a_min=0, a_max=1500.00, inplace=True) if x.name in columns else x)
print('Dataset shape' + str(dv.shape))
print('Lifters in Squat, Bench, Deadlift competitions: ' + str(dv['Sex'].count()))
dv.isnull().sum()

Dataset shape(395708, 22)
Lifters in Squat, Bench, Deadlift competitions: 395708

Sex                     0
Event                   0
Equipment               0
Age                     0
BodyweightKg            0
Squat1Kg           169146
Squat2Kg           171653
Squat3Kg           177868
Squat4Kg           393317
Best3SquatKg          177
Bench1Kg           169181
Bench2Kg           171184
Bench3Kg           177819
Bench4Kg           393594
Best3BenchKg          182
Deadlift1Kg        169016
Deadlift2Kg        172429
Deadlift3Kg        182072
Deadlift4Kg        392174
Best3DeadliftKg       166
TotalKg                 0
Wilks                   0
dtype: int64

## Last modifications to use the data for training
Source: https://developers.google.com/machine-learning/data-prep/transform/normalization
First normalisation of data:
- Age: z-score scaling to account for outliers
- BodyweightKg:

In [22]:
dv

,Sex,Event,Equipment,Age,BodyweightKg,Squat1Kg,Squat2Kg,Squat3Kg,Squat4Kg,Best3SquatKg,...,Bench3Kg,Bench4Kg,Best3BenchKg,Deadlift1Kg,Deadlift2Kg,Deadlift3Kg,Deadlift4Kg,Best3DeadliftKg,TotalKg,Wilks
0,F,SBD,Wraps,29.0,59.8,80.0,92.5,105.0,NaN,105.0,...,55.0,NaN,55.0,110.0,120.0,130.0,NaN,130.0,290.0,324.16
1,F,SBD,Wraps,29.0,58.5,100.0,110.0,120.0,NaN,120.0,...,67.5,NaN,67.5,130.0,140.0,145.0,NaN,145.0,332.5,378.07
2,F,SBD,Wraps,23.0,60.0,-105.0,-105.0,105.0,NaN,105.0,...,-75.0,NaN,72.5,132.5,-140.0,-140.0,NaN,132.5,310.0,345.61
3,F,SBD,Wraps,45.0,104.0,120.0,130.0,140.0,NaN,140.0,...,80.0,NaN,80.0,150.0,160.0,170.0,NaN,170.0,390.0,321.25
4,F,SBD,Wraps,37.0,74.0,127.5,135.0,142.5,NaN,142.5,...,82.5,NaN,82.5,125.0,135.0,145.0,NaN,145.0,370.0,354.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395703,M,SBD,Raw,65.5,78.0,195.0,202.5,215.0,NaN,215.0,...,115.0,NaN,115.0,195.0,207.5,-212.5,NaN,207.5,537.5,372.98
395704,M,SBD,Raw,67.5,72.7,185.0,195.0,200.0,NaN,200.0,...,NaN,NaN,70.0,-235.0,235.0,-250.5,NaN,235.0,505.0,367.91
395705,M,SBD,Raw,60.5,73.5,160.0,170.0,175.0,NaN,175.0,...,87.5,NaN,87.5,180.0,190.0,-195.0,NaN,190.0,452.5,327.07
395706,M,SBD,Raw,55.5,63.5,90.0,100.0,110.0,NaN,110.0,...,-100.0,NaN,95.0,140.0,160.0,170.0,NaN,170.0,375.0,304.16
395707,M,SBD,Raw,62.5,94.4,140.0,150.0,160.0,NaN,160.0,...,NaN,NaN,100.0,160.0,170.0,180.0,NaN,180.0,440.0,274.48

In [23]:
# Convert string data to numeric
numericSex = {'M': 1, 'F': 0}
# Boolean for equipment
numericEquipment = {'Raw': 0, 'Wraps': 1, 'Multi-ply': 1, 'Single-ply': 1, 'Straps': 1}

dv.Sex = [numericSex[item] for item in dv.Sex]
dv.Equipment = [numericEquipment[item] for item in dv.Equipment]

# Normalise the data, scaling to values between 0-1
# scaler = MinMaxScaler(feature_range=(0,1))
# data_b[columns] = scaler.fit_transform(data_b[columns])

In [33]:
# define the target variable (dependent variable) as y
# x = dv['BodyweightKg', 'Equipment', 'Age', 'Squat1Kg', 'Squat2Kg', 'Squat3Kg', 'Squat4Kg', 'Best3SquatKg', 'Bench1Kg', 'Bench2Kg', 'Bench3Kg', 'Bench4Kg', 'Best3BenchKg', 'Deadlift1Kg', 'Deadlift2Kg', 'Deadlift3Kg', 'Deadlift4Kg', 'Best3DeadliftKg']
x = dv.filter(items=['Sex','BodyweightKg', 'Equipment', 'Age', 'Squat1Kg', 'Squat2Kg', 'Squat3Kg', 'Squat4Kg', 'Best3SquatKg', 'Bench1Kg', 'Bench2Kg', 'Bench3Kg', 'Bench4Kg', 'Best3BenchKg', 'Deadlift1Kg', 'Deadlift2Kg', 'Deadlift3Kg', 'Deadlift4Kg', 'Best3DeadliftKg'])
y = dv['Sex']
# create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=3, shuffle=True)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(296781, 19) (296781,)
(98927, 19) (98927,)

In [35]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(12, input_dim=7, kernel_initializer='uniform', activation='relu'))
model.add(Dense(8, kernel_initializer='uniform', activation='relu'))
model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

/Users/jlsaldana/.pyenv/versions/3.7.6/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(12, input_dim=7, activation="relu", kernel_initializer="uniform")`
  """
/Users/jlsaldana/.pyenv/versions/3.7.6/lib/python3.7/site-packages/ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(8, activation="relu", kernel_initializer="uniform")`

/Users/jlsaldana/.pyenv/versions/3.7.6/lib/python3.7/site-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="uniform")`
  import sys